apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/sleepr-398121/reservations/production
          name: reservations
          env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
